---
title: "antncos"
author: "Zach Brown"
date: "February 26, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

1. Load packages
```{r}
library(tidyverse)
library(RColorBrewer)
library(forcats)
library(lubridate)
library(dbplyr)
```

2. load and wrangle data
```{r}
allsbcoants<- read_csv("newsbcoants.csv")


#make df way less obnoxious
antssimple <-allsbcoants %>%
#selecting columns to keep for data analysis
  select(
    order, family, scientificName, year, month, eventDate, verbatimEventDate, samplingProtocol, habitat, country, stateProvince, county, municipality, decimalLatitude, decimalLongitude, recordedBy, individualCount)

#puts months in order numerically and abbr
antssimple$month = factor(antssimple$month, levels = month.name, labels = month.abb)

#sum of all individual ants from NCOS
sumant <- sum(antssimple$individualCount, na.rm = FALSE)

antsncos<-antssimple %>%
#excluded anything that doesnt have UCSB Arthropod Survey
  filter(recordedBy =="UCSB Arthropod Survey")%>%
#exluded anything that doesn't have a genera level determination
  filter(scientificName !="Formicidae")

#Filters out ants not identified to genus
antssimplegenera<-antssimple%>%
  filter(scientificName !="Formicidae")%>%
  filter(scientificName !="Myrmicinae")

#sum of all ants in ncos
sumantncos <- sum(antsncos$individualCount, na.rm = FALSE)

#this is just scientific names and individual count dataframe
antstotalncos<-antsncos %>%
  select(scientificName, individualCount)

#Temnothorax dataframe only, NCOS
temno<-antstotalncos%>%
  filter(scientificName == "Temnothorax")
#sum of individual Temnothorax
sumtemno<-sum(temno$individualCount)

#L. humile dataframe only, NCOS
lhumile<-antstotalncos%>%
  filter(scientificName=="Linepithema humile")
#sum of individual L. humile
sumlhumile<-sum(lhumile$individualCount)

#Solenopsis dataframe only, NCOS
solenopsis<-antstotalncos%>%
  filter(scientificName=="Solenopsis")
#sum of individual Solenopsis
sumsol<-sum(solenopsis$individualCount)

#Monomorium dataframe only, NCOS
mono<-antstotalncos%>%
  filter(scientificName=="Monomorium")
#sum of individual Monomorium
summono<-sum(mono$individualCount)

#Hypoponera dataframe only, NCOS
hypo<-antstotalncos%>%
  filter(scientificName=="Hypoponera")
#sum of individual Hypoponera
sumhypo<-sum(hypo$individualCount)

```

3. data exploration
```{r}
#Graph of each genus of ant with actual counts

scinameabund<- ggplot(mutate
                     (antsncos, scientificName = fct_infreq(scientificName))) + 
  geom_bar(
    aes(x = scientificName, fill= scientificName, weight=individualCount))+
  labs(x="Scientific Name", y="Number of Individual Ants", title = "Collected Ants Before Restoration") +
  theme_bw()+
  theme(legend.position = "top",
        legend.title = element_blank(),
        panel.border = element_blank(), 
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        axis.line = element_line(colour = "black"),
        axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank())+
  scale_y_continuous(expand = c(0,0), limits = c(0,1600))

scinameabund
########################################################################################
#Bar plot of trap type with actual counts

traptype <- scinameabund + facet_wrap(~samplingProtocol) +labs(title = "Ants Collected by Trap")+
  scale_y_continuous(expand = c(0,0), limits = c(0,800))
traptype

########################################################################################
#Plot of ants by month

yearant <- scinameabund + facet_wrap(~month) + labs(title = "Ants Collected by Month")+
  scale_y_continuous(expand = c(0,0), limits = c(0,900))
yearant

#######################################################################################
#Habitats need to be condensed

habant <- scinameabund + facet_wrap(~habitat) + labs(title = "Ant abundance by habitat")
habant

#######################################################################################
#Histogram of ant occurences and genus

ggplot(antssimplegenera, aes(x = year, fill=scientificName)) +
      geom_histogram(position = "identity", binwidth=0.5, na.rm = FALSE, show.legend = FALSE)+
  theme_bw()+
  theme(panel.border = element_blank(), 
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        axis.line = element_line(colour = "black"),
        axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank())+
  labs(x= "Year Collected", y= "Number of Occurences", title = "Specimens Collected in Last 70 years (1949-2019)")+
  scale_y_continuous(expand = c(0,0), limits = c(0,150))

#######################################################################################


```

